apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-web
  namespace: test-nfs
spec:
  selector:
    matchLabels:
      app: nfs-web
  template:
    metadata:
      labels:
        app: nfs-web
    spec:
      containers:
      - name: nfs-web
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: web 
            containerPort: 80
        volumeMounts:
          - name: nfs
            mountPath: /usr/share/nginx/html
      volumes: 
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
